### ISSUE TITLE
EsLint Error: Unable to resolve path to module 'react-native-torch'

### ISSUE THREAD

**Issue by ridvanaltun** [ludo/react-native-torch#22]
`Unable to resolve path to module 'react-native-torch'.`

Something wrong in this library.

**Comment by ghost** [comment]
I also faced  the same issue. solution for this go to "nodemodules/react-native-torch/package.json" file and change "main": "index" to "main": "index.android.js" for android.
But Torch will work in both the cases. It is not compulsory to change.

**Comment by ridvanaltun** [comment]
> I also faced the same issue. solution for this go to "nodemodules/react-native-torch/package.json" file and change "main": "index" to "main": "index.android.js" for android.
> But Torch will work in both the cases. It is not compulsory to change.

Thanks for the solution.
