### ISSUE TITLE
Doesn't work on Android 5.0 lollipop

### ISSUE THREAD

**Issue by basilwood** [ludo/react-native-torch#3]
Added permission for camera and flashlight in Androidmanifest.xml still, the flashlight doesn't turn ON on lollipop. Couldn't check on Android 5.1 but works above marshmallow.

**Comment by ludo** [comment]
Could you try with beta version 1.1.0: `npm install react-native-torch@next`? Older versions of this package only worked with Android >= 6, but version 1.1.0 should support older Android versions. Let me know if this helps!

**Comment by basilwood** [comment]
Hi
I tried the beta version. Now I get this error
"Loading dependency graph, done.
Bundling `index.js`  [development, non-minified]  0.0% (1/478), failed.
error: bundling failed: UnableToResolveError: Unable to resolve module `react-native-torch` from `/Users/ajuvignesh/own/Flashlight/src/App.js`: Module does not exist in the module map or in these directories:
  /Users/ajuvignesh/own/Flashlight/node_modules"
Cleaned and reinstalled node_modules but no joy.

**Comment by zygama** [comment]
Hi,
i have the same problem with 1.1.0

**Comment by GeorgianSorinMaxim** [comment]
@basilwood @zygama You need to stop and re-run npm start -- --reset-cache.

**Comment by dac09** [comment]
Hello, I'll push up a fix for the 'unable to resolve module' issue for 1.1.0 in a couple of hours. 

I think it's something to do with the platform specific extensions, which don't seem to be supported inside a node module. 

I have it running locally i.e. not installed through node_modules but cloned into a libs folder and it works ok.

**Comment by dac09** [comment]
Created a PR for it (it's a little hard to test without it being published), but think it should solve the problem. Please let me know when you have had a chance to try!

**Comment by ludo** [comment]
I've published v1.1.1 to npm (`npm install react-native-torch@next`). It fixes the 'unable to resolve' issue for me.

@dac09 thanks for your contribution/help!

**Comment by zygama** [comment]
it works now thank you :)
